version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=mydatabase
      - PGUSER=myuser
      - PGPASSWORD=mypassword
